### ISSUE TITLE
Increasing max_depth results in an overall darker image

### ISSUE THREAD

**Issue by DandongExpress** [miguelvc6/ray-tracing#1]
Hello, great work, I just started reading your code, and when testing the effect of the code, I noticed that as the max_depth parameter increases, the overall brightness of the rendered image will become darker. Could you explain the possible reasons?

**Comment by miguelvc6** [comment]
The ray tracing system simulates light rays emitted from the viewpoint. When a light ray bounces on a material, the object absorbs some of the light (except if it is fully reflective, like a mirror). The higher the value of max_depth, the more bounces are simulated, so the more of it is absorbed. 
This is not a problem in an open space, because the light will eventually go away and stop bouncing, but in an enclosed space it will keep bouncing and the light will keep being absorbed. In the case of the Cornell's box scenario it is completly enclosed so this effect is very high, as you can see in the images I have in the repository.
If I had a light source in the scenario it would not happen, but they are not implemented.
Please bear in mind that I do not have expertise in graphic engines, and I can be wrong about this.

**Comment by DandongExpress** [comment]
OK, thank you very much for your answer, I've got satisfactory results in an open environment. 
I salute you for your concise and readable code, many computer vision github projects are now frustratingly complicated.
